// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcxS753OsUAVdOSPJBpnzjhxgGr5gwNg',
    appId: '1:574878357929:web:10d7cbd883f39971f5ccb8',
    messagingSenderId: '574878357929',
    projectId: 'toohak-58bc4',
    authDomain: 'toohak-58bc4.firebaseapp.com',
    storageBucket: 'toohak-58bc4.appspot.com',
    measurementId: 'G-T00Q6NCL7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6SHapgwkcRo5aLzh8JY70D9rSEO7bBVU',
    appId: '1:574878357929:android:9fc5e960be082852f5ccb8',
    messagingSenderId: '574878357929',
    projectId: 'toohak-58bc4',
    storageBucket: 'toohak-58bc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLbvlQyVPw76KdsU4WC9M6YNlGozsEoak',
    appId: '1:574878357929:ios:44459fe3e834afe5f5ccb8',
    messagingSenderId: '574878357929',
    projectId: 'toohak-58bc4',
    storageBucket: 'toohak-58bc4.appspot.com',
    iosBundleId: 'com.example.toohak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLbvlQyVPw76KdsU4WC9M6YNlGozsEoak',
    appId: '1:574878357929:ios:701fed5e345c64a5f5ccb8',
    messagingSenderId: '574878357929',
    projectId: 'toohak-58bc4',
    storageBucket: 'toohak-58bc4.appspot.com',
    iosBundleId: 'com.example.toohak.RunnerTests',
  );
}
